application: bulutkarakayaweb
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|eot|svg|ttf|woff|woff2|rar|pdf|exe|application|manifest|dll|xml|swf|unity3d|xap))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|eot|svg|ttf|woff|woff2|rar|pdf|exe|application|manifest|dll|xml|swf|unity3d|xap))

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt 

- url: .*
  script: main.py
